In [1]:
import seaborn as sns
titanic = sns.load_dataset('titanic')

In [14]:
from scipy import stats

In [4]:
import pandas as pd
import numpy as np

In [2]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [17]:
contin = pd.crosstab(index = titanic['class'], columns = titanic['sex'])
contin

sex     female  male
class               
First       94   122
Second      76   108
Third      144   347

In [13]:
contin.values

array([[ 94, 122],
       [ 76, 108],
       [144, 347]], dtype=int64)

In [15]:
stat, p, dof, expected = stats.chi2_contingency(contin.values)

In [16]:
p

0.00020638864348233114

In [18]:
expected

array([[ 76.12121212, 139.87878788],
       [ 64.84399551, 119.15600449],
       [173.03479237, 317.96520763]])

In [19]:
contin = pd.crosstab(index = titanic['survived'], columns = titanic['sex'])
contin

sex       female  male
survived              
0             81   468
1            233   109

In [20]:
contin.values

array([[ 81, 468],
       [233, 109]], dtype=int64)

In [21]:
stat, p, dof, expected = stats.chi2_contingency(contin.values)

In [22]:
p

1.1973570627755645e-58

In [23]:
expected

array([[193.47474747, 355.52525253],
       [120.52525253, 221.47474747]])

In [24]:
contin = pd.crosstab(index = titanic['survived'], columns = titanic['class'])
contin

class     First  Second  Third
survived                      
0            80      97    372
1           136      87    119

In [25]:
contin.values

array([[ 80,  97, 372],
       [136,  87, 119]], dtype=int64)

In [26]:
stat, p, dof, expected = stats.chi2_contingency(contin.values)

In [27]:
p

4.549251711298793e-23

In [28]:
expected

array([[133.09090909, 113.37373737, 302.53535354],
       [ 82.90909091,  70.62626263, 188.46464646]])